from models.domain_policy import DomainPolicy, EventPolicy, PriorityTier, GlobalPolicySettings

def get_ecommerce_policy() -> DomainPolicy:
    return DomainPolicy(
        domainName="E-Commerce Flash Sale",
        description="High-throughput adaptive event processing for flash-sales and e-commerce spikes",
        version="v1.0.0",
        eventTypes=[
            EventPolicy(
                type="payment.webhook.charge",
                displayName="Payment Webhook",
                description="Real-time financial checkout charges and payment confirmations",
                priority="P0",
                critical=True,
                slaMs=50,
                batchable=False,
                maxBatchSize=1,
                preferredStrategy="stream",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.7,
                dependencies=["payment-gateway", "ledger-db"]
            ),
            EventPolicy(
                type="order.fulfillment.created",
                displayName="Order Fulfillment",
                description="Purchase order intake, fulfillment triggers, and order reservation",
                priority="P0",
                critical=True,
                slaMs=100,
                batchable=False,
                maxBatchSize=1,
                preferredStrategy="stream",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.8,
                dependencies=["order-service", "warehouse-api"]
            ),
            EventPolicy(
                type="inventory.warehouse.sync",
                displayName="Inventory Sync",
                description="Stock reservation and warehouse inventory synchronization",
                priority="P1",
                critical=False,
                slaMs=2000,
                batchable=True,
                maxBatchSize=100,
                preferredStrategy="batch",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.5,
                dependencies=["inventory-db"]
            ),
            EventPolicy(
                type="activity.user.clickstream",
                displayName="User Clickstream",
                description="User sessions, product browsing telemetry, and cart updates",
                priority="P2",
                critical=False,
                slaMs=10000,
                batchable=True,
                maxBatchSize=250,
                preferredStrategy="defer",
                canDefer=True,
                canShed=False,
                retryable=False,
                idempotencyRequired=False,
                processingCost=0.3,
                dependencies=["analytics-pipeline"]
            ),
            EventPolicy(
                type="system.telemetry.debug_log",
                displayName="Telemetry & Logs",
                description="Debug traces, worker metrics, and system audit logs",
                priority="P3",
                critical=False,
                slaMs=30000,
                batchable=True,
                maxBatchSize=500,
                preferredStrategy="shed",
                canDefer=True,
                canShed=True,
                sheddingThreshold=0.70,
                retryable=False,
                idempotencyRequired=False,
                processingCost=0.2,
                dependencies=["log-aggregator"]
            )
        ],
        priorityTiers=[
            PriorityTier(code="P0", name="Critical Financial", description="Streaming lane. Zero drop.", targetSlaMs=50, allowShedding=False),
            PriorityTier(code="P1", name="High Inventory", description="Micro-batching under load.", targetSlaMs=2000, allowShedding=False),
            PriorityTier(code="P2", name="Normal Activity", description="Spillover deferral during peaks.", targetSlaMs=10000, allowShedding=False),
            PriorityTier(code="P3", name="Low Telemetry", description="Controlled statistical sampling permitted.", targetSlaMs=30000, allowShedding=True),
        ],
        globalSettings=GlobalPolicySettings(
            baselineTrafficRate=1000,
            spikeTrafficRate=20000,
            maxQueueCapacity=10000,
            maxBatchSizeLimit=1000,
            maxDeferWindowSecondsLimit=300,
            maxSamplingRateLimit=0.90
        )
    )

def get_hospital_policy() -> DomainPolicy:
    return DomainPolicy(
        domainName="Hospital Disaster Management",
        description="Mass casualty and disaster response medical coordination pipeline",
        version="v1.0.0",
        eventTypes=[
            EventPolicy(
                type="emergency.patient.alert",
                displayName="Patient Emergency Alert",
                description="Life-critical patient trauma alerts, defibrillator alerts, vitals collapse",
                priority="P0",
                critical=True,
                slaMs=50,
                batchable=False,
                maxBatchSize=1,
                preferredStrategy="stream",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.9,
                dependencies=["triage-dispatch", "icu-pager"]
            ),
            EventPolicy(
                type="ambulance.arrival.triage",
                displayName="Ambulance Arrival",
                description="Inbound ambulance trauma arrivals and paramedic transfer reports",
                priority="P0",
                critical=True,
                slaMs=100,
                batchable=False,
                maxBatchSize=1,
                preferredStrategy="stream",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.7,
                dependencies=["er-bay-manager"]
            ),
            EventPolicy(
                type="icu.bed.status",
                displayName="ICU Bed Availability",
                description="ICU / OR room occupancy telemetry and bed reservation sync",
                priority="P1",
                critical=False,
                slaMs=1500,
                batchable=True,
                maxBatchSize=50,
                preferredStrategy="batch",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.5,
                dependencies=["hospital-facilities-db"]
            ),
            EventPolicy(
                type="medical.inventory.blood_units",
                displayName="Blood & Medical Inventory",
                description="Blood bank units, oxygen pressure, and emergency medication supplies",
                priority="P1",
                critical=False,
                slaMs=2000,
                batchable=True,
                maxBatchSize=100,
                preferredStrategy="batch",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.5,
                dependencies=["pharmacy-db"]
            ),
            EventPolicy(
                type="doctor.shift.notifications",
                displayName="Staff Notifications",
                description="Doctor on-call alerts, shift rotations, and non-emergency broadcast notices",
                priority="P2",
                critical=False,
                slaMs=8000,
                batchable=True,
                maxBatchSize=200,
                preferredStrategy="defer",
                canDefer=True,
                canShed=False,
                retryable=False,
                idempotencyRequired=False,
                processingCost=0.4,
                dependencies=["staff-app"]
            ),
            EventPolicy(
                type="hospital.analytics.reports",
                displayName="Routine Reports & Logs",
                description="Facility temperature sensors, shift metrics, routine diagnostic reports",
                priority="P3",
                critical=False,
                slaMs=30000,
                batchable=True,
                maxBatchSize=500,
                preferredStrategy="shed",
                canDefer=True,
                canShed=True,
                sheddingThreshold=0.75,
                retryable=False,
                idempotencyRequired=False,
                processingCost=0.2,
                dependencies=["medical-records-archive"]
            )
        ],
        priorityTiers=[
            PriorityTier(code="P0", name="Critical Life Safety", description="Instant stream delivery. Zero drop.", targetSlaMs=50, allowShedding=False),
            PriorityTier(code="P1", name="High Medical Resources", description="Micro-batching under load.", targetSlaMs=2000, allowShedding=False),
            PriorityTier(code="P2", name="Normal Operational", description="Deferred to disk spillover during mass casualty surge.", targetSlaMs=8000, allowShedding=False),
            PriorityTier(code="P3", name="Low Telemetry", description="Controlled statistical sampling permitted.", targetSlaMs=30000, allowShedding=True),
        ],
        globalSettings=GlobalPolicySettings(
            baselineTrafficRate=1000,
            spikeTrafficRate=25000,
            maxQueueCapacity=15000,
            maxBatchSizeLimit=1000,
            maxDeferWindowSecondsLimit=300,
            maxSamplingRateLimit=0.90
        )
    )

def get_education_policy() -> DomainPolicy:
    return DomainPolicy(
        domainName="Education / Result Publishing Day",
        description="Mass concurrent examination result publishing to 100,000+ students simultaneously",
        version="v1.0.0",
        eventTypes=[
            EventPolicy(
                type="result.lookup.query",
                displayName="Student Result Lookup",
                description="Student scorecard query and grade report generation",
                priority="P0",
                critical=True,
                slaMs=80,
                batchable=False,
                maxBatchSize=1,
                preferredStrategy="stream",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.6,
                dependencies=["grades-cache", "student-db"]
            ),
            EventPolicy(
                type="student.auth.session",
                displayName="Student Authentication",
                description="Roll number verification and SSO authentication requests",
                priority="P0",
                critical=True,
                slaMs=120,
                batchable=False,
                maxBatchSize=1,
                preferredStrategy="stream",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.7,
                dependencies=["auth-server"]
            ),
            EventPolicy(
                type="payment.fee.verification",
                displayName="Fee / Transcript Payment",
                description="Re-evaluation fee processing and digital transcript purchase verification",
                priority="P1",
                critical=False,
                slaMs=2000,
                batchable=True,
                maxBatchSize=80,
                preferredStrategy="batch",
                canDefer=False,
                canShed=False,
                retryable=True,
                idempotencyRequired=True,
                processingCost=0.6,
                dependencies=["payment-gateway"]
            ),
            EventPolicy(
                type="sms.email.notification",
                displayName="Notification Dispatch",
                description="SMS result score alerts and email scorecard delivery queues",
                priority="P2",
                critical=False,
                slaMs=12000,
                batchable=True,
                maxBatchSize=300,
                preferredStrategy="defer",
                canDefer=True,
                canShed=False,
                retryable=False,
                idempotencyRequired=False,
                processingCost=0.4,
                dependencies=["sms-gateway"]
            ),
            EventPolicy(
                type="access.audit.clickstream",
                displayName="Audit Telemetry & Clicks",
                description="Page view analytics, CDN edge logs, and session telemetry",
                priority="P3",
                critical=False,
                slaMs=30000,
                batchable=True,
                maxBatchSize=500,
                preferredStrategy="shed",
                canDefer=True,
                canShed=True,
                sheddingThreshold=0.70,
                retryable=False,
                idempotencyRequired=False,
                processingCost=0.2,
                dependencies=["analytics-lake"]
            )
        ],
        priorityTiers=[
            PriorityTier(code="P0", name="Critical Result Lookup", description="Zero-drop streaming scorecard queries.", targetSlaMs=80, allowShedding=False),
            PriorityTier(code="P1", name="High Payment Verification", description="Batched fee & transcript processing.", targetSlaMs=2000, allowShedding=False),
            PriorityTier(code="P2", name="Normal Notifications", description="Spillover queue for non-blocking email/SMS dispatch.", targetSlaMs=12000, allowShedding=False),
            PriorityTier(code="P3", name="Low Web Analytics", description="Statistical sampling permitted during peak query load.", targetSlaMs=30000, allowShedding=True),
        ],
        globalSettings=GlobalPolicySettings(
            baselineTrafficRate=1000,
            spikeTrafficRate=35000,
            maxQueueCapacity=20000,
            maxBatchSizeLimit=1000,
            maxDeferWindowSecondsLimit=300,
            maxSamplingRateLimit=0.90
        )
    )

PREDEFINED_DOMAINS = {
    "ecommerce": get_ecommerce_policy(),
    "hospital": get_hospital_policy(),
    "education": get_education_policy(),
}
